services:
  iseetv:
    container_name: ISeeTV
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "1313:3000"  # Frontend
      - "1314:8000"  # Backend
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data:/app/data
      - /app/frontend/node_modules
    user: "nobody:users"
    environment:
      - DATABASE_URL=sqlite:////app/data/sql_app.db

volumes:
  data:

networks:
  default:
    driver: bridge