services:
  init-db:
    container_name: iseetv-init-db
    image: python:3.11-slim
    volumes:
      - ./backend:/app
      - ./data:/data
    working_dir: /app
    command: >
      /bin/bash -c "
        python init_db.py
      "

  frontend:
    container_name: iseetv-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1313:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: iseetv-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1314:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    networks:
      - app-network
    user: "1000:1000"
    depends_on:
      init-db:
        condition: service_completed_successfully

volumes:
  data:

networks:
  app-network:
    driver: bridge
