# Frontend (Vite) Dev Image
FROM node:22-slim AS frontend

WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./

# Backend (FastAPI) Dev Image
FROM ghcr.io/astral-sh/uv:python3.11-bookworm-slim AS backend

WORKDIR /app

# Copy project files
COPY backend/pyproject.toml backend/uv.lock* ./

# Install dependencies
RUN uv sync --frozen --no-cache

# Copy the rest of the backend code
COPY backend/ /app
