services:
  iseetv:
    container_name: ISeeTV
    build:
      context: .
    ports:
      - "1313:80"  # Nginx
    volumes:
      - ./data:/data
    runtime: nvidia
    environment:
      - FASTAPI_URL=/api  # Frontend will use relative API URL via Nginx
      - NVIDIA_VISIBLE_DEVICES=GPU-25f5d0be-15d5-fcff-be10-c1afca13d69a
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
