# This workflow is used to run linting and formatting checks on the codebase.
# It is triggered when a pull request is created or updated.

name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install uv==0.7.20
          cd backend
          uv sync --frozen

      - name: Install Frontend dependencies
        run: |
          cd frontend
          pnpm ci

      - name: Run linting
        run: |
          cd backend
          uv run mypy .
          uv run ruff check .
          uv run black --check .

      - name: Run linting
        run: |
          cd frontend
          pnpm run lint
