name: Issue Closed
run-name: ${{ github.event.issue.title }} was closed
on:
  issues:
    types:
      - closed

permissions:
  issues: write

jobs:
  remove-inprogress-label:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to set up the environment
      - name: Checkout repository
        uses: actions/checkout@v3
      # Use GitHub CLI to remove the "inprogress" label
      - name: Remove inprogress label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --remove-label inprogress
