name: Update README on Label Change

on:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  contents: write

jobs:
  update-readme:
    if: github.event.label.name == 'inprogress'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run README update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .scripts/update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README due to label change on issue ${GITHUB_EVENT_ISSUE_NUMBER}"
          git push
