name: Update README on Label Change

on:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  contents: write

jobs:
  update-readme:
    if: github.event.label.name == 'inprogress'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Temporary Access Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.ISEETV_APP_ID }}
          application_private_key: ${{ secrets.ISEETV_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run README update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .scripts/update_readme.py

      - name: Create and Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          git config --global user.name "ReadmeUpdater"
          git config --global user.email "ReadmeUpdater@users.noreply.github.com"
          
          # Create new branch
          branch_name="readme-update-${GITHUB_SHA::8}"
          git checkout -b $branch_name
          
          # Commit changes
          git add README.md
          git commit -m "Update README due to label change on issue #${{ github.event.issue.number }}"
          git push origin $branch_name
          
          # Create and merge PR using GitHub CLI
          gh auth login --with-token <<< "${{ steps.get_workflow_token.outputs.token }}"
          pr_url=$(gh pr create --title "Update README" --body "Automated README update" --base master --head $branch_name)
          gh pr merge --auto --merge "$pr_url"
